mitasny/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('tasks.urls', namespace='tasks')),
]

tasks/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .tasks_user import TasksUserList, TasksUserDetail, TasksUserRegister, TasksUserUpdate, TasksUserDelete
from .project import ProjectList, ProjectListWeekly, ProjectDetail, ProjectWeekly, ProjectCreate, ProjectUpdate, ProjectDelete
from .task import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskMove, TaskSetPhaseTo, TaskDelete

app_name = 'tasks'

urlpatterns = [
    url(r'^$', ProjectList.as_view(), name='home'),
    url(r'^register/$', TasksUserRegister.as_view(), name='register'),
    url(r'^user/(?P<slug>[\w\.-]+)/delete/$', login_required(TasksUserDelete.as_view()), name='user_delete'),
    url(r'^user/(?P<slug>[\w\.-]+)/edit/$', login_required(TasksUserUpdate.as_view()), name='user_update'),
    url(r'^user/(?P<slug>[\w\.-]+)/$', TasksUserDetail.as_view(), name='user'),
    url(r'^project/create/$', login_required(ProjectCreate.as_view()), name='project_create'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/create/$', login_required(TaskCreate.as_view()), name='task_create'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/set_phase_to/(?P<phase>[\w\.-]+)/$', login_required(TaskSetPhaseTo.as_view()), name='task_set_phase_to'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/move/(?P<dir>[\w\.-]+)/$', login_required(TaskMove.as_view()), name='task_move'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/edit/$', TaskUpdate.as_view(), name='task_update'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/delete/$', TaskDelete.as_view(), name='task_delete'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/$', TaskDetail.as_view(), name='task'),
    url(r'^project/(?P<slug>[\w\.-]+)/tab/(?P<tab>[\w\.-]+)/$', ProjectDetail.as_view(), name='project_tab'),
    url(r'^project/(?P<slug>[\w\.-]+)/weekly_report.html$', ProjectWeekly.as_view(), name='project_weekly'),
    url(r'^project/(?P<slug>[\w\.-]+)/edit/$', login_required(ProjectUpdate.as_view()), name='project_update'),
    url(r'^project/(?P<slug>[\w\.-]+)/delete/$', login_required(ProjectDelete.as_view()), name='project_delete'),
    url(r'^project/(?P<slug>[\w\.-]+)/$', ProjectDetail.as_view(), name='project'),
    url(r'^projects/weekly/$', ProjectListWeekly.as_view(), name='projects_weekly'),
    url(r'^projects/$', ProjectList.as_view(), name='projects'),
    url(r'^users/$', TasksUserList.as_view(), name='users'),
    url(r'^tasks/$', TaskList.as_view(), name='tasks'),
]

tasks/models.py
import datetime
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy
from django.contrib.auth.models import User
from .calculate_finish_date import calculate_finish_date


class Project(models.Model):
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URL.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('title'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_projects', on_delete=models.CASCADE)
    edited = models.DateTimeField(auto_now=True)
    edited_by = models.ForeignKey(User, null=True, related_name='edited_projects', on_delete=models.CASCADE)

    @property
    def total_work_left(self):
        if self.tasks.count() == 0:
            return 0

        sum_dict = self.tasks.aggregate(models.Sum('work_left'))
        return sum_dict['work_left__sum']

    @property
    def total_work_left_list(self):
        day_list = []
        total_work = self.total_work_left
        if total_work == 0:
            return day_list

        day = datetime.date.today()
        one_day = datetime.timedelta(days=1)
        for i in range(0, self.total_work_left):
            day_list.append(day)
            day += one_day
            if day.weekday() == 5:
                day += one_day
            if day.weekday() == 6:
                day += one_day

        return day_list

    @property
    def total_work_left_weeks_list(self):
        return range(0, self.total_work_left / 5)

    @property
    def total_work_left_string(self):
        days = self.total_work_left
        weeks = int(days / 5)
        days = days % 5
        months = int(weeks / 4)
        weeks = weeks % 4
        if months > 0:
            return '%d month(s), %d week(s), %d day(s)' % (months, weeks, days)
        elif weeks > 0:
            return '%d week(s), %d day(s)' % (weeks, days)
        else:
            return '%d day(s)' % days

    @property
    def finish_date(self):
        days_left = self.total_work_left
        start_date = datetime.date.today()
        return calculate_finish_date(start_date, days_left)

    def can_edit(self, user):
        if user == self.created_by:
            return True
        return False

    def tasks_by_phase(self, phase):
        return Task.objects.filter(project=self, phase=phase).order_by('order')

    def tasks_by_phase_name(self, phase_name):
        phases = Phase.objects.filter(name=phase_name)
        if phases.count() == 1:
            phase = phases.first()
            return self.tasks_by_phase(phase)
        return Task.objects.none()

    @property
    def tasks_done(self):
        return self.tasks_by_phase_name('done')

    @property
    def tasks_finished(self):
        return self.tasks_by_phase_name('finished')

    @property
    def tasks_ongoing(self):
        return self.tasks_by_phase_name('ongoing')

    @property
    def tasks_continuing(self):
        return self.tasks_by_phase_name('continuing')

    @property
    def tasks_pending(self):
        return self.tasks_by_phase_name('pending')

    @property
    def impediments(self):
        return self.tasks_by_phase_name('impediment')

    @property
    def tasks_unfinished(self):
        excluded_phases = ['finished', 'done', 'impediment']
        tasks = Task.objects.filter(project=self)
        for phase_name in excluded_phases:
            tasks = tasks.exclude(phase__name=phase_name)

        return tasks

    @property
    def tasks_not_done(self):
        done = Phase.objects.get(name='done')
        return Task.objects.filter(project=self).exclude(phase=done)

    @property
    def tasks_last_week(self):
        finished_or_continuing = models.Q(phase__name='finished') | models.Q(phase__name='continuing')
        tasks = Task.objects.filter(project=self).filter(finished_or_continuing)
        return tasks

    @property
    def tasks_this_week(self):
        ongoing_or_continuing = models.Q(phase__name='ongoing') | models.Q(phase__name='continuing')
        tasks = Task.objects.filter(project=self).filter(ongoing_or_continuing)
        return tasks

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tasks:project', args=[self.name])


class Priority(models.Model):
    # Idea, Nice(to have), Minor, Normal, Major, Critical
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URLs.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('title'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    order = models.PositiveSmallIntegerField(default=0)


class TaskStatus(models.Model):
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URLs.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('title'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    order = models.PositiveSmallIntegerField(default=0)


class Phase(models.Model):
    # Blocked, Pending, Ongoing, (Recently)Finished, Done
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URLs.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('title'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    order = models.PositiveSmallIntegerField(default=0)
    element_class = models.CharField(default='', blank=True, max_length=250)  # CSS class to be used in HTML

    def __str__(self):
        # return '%d:%s:%s' % (self.order, self.name, self.title)
        return self.title

    class Meta:
        ordering = ['order', 'title']


class Task(models.Model):
    project = models.ForeignKey(Project, null=False, related_name='tasks', on_delete=models.CASCADE)
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URL.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('task'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    order = models.PositiveSmallIntegerField(default=0)
    priority = models.ForeignKey(Priority, null=True, on_delete=models.CASCADE)
    phase = models.ForeignKey(Phase, null=True, blank=True, on_delete=models.CASCADE)
    # status = models.ForeignKey(TaskStatus, null=True)
    owner = models.ForeignKey(User, null=True, related_name='tasks', on_delete=models.CASCADE)
    work_done = models.PositiveSmallIntegerField(default=0)
    work_left = models.PositiveSmallIntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_tasks', on_delete=models.CASCADE)
    edited = models.DateTimeField(auto_now=True)
    edited_by = models.ForeignKey(User, null=True, related_name='edited_tasks', on_delete=models.CASCADE)

    @property
    def work_left_list(self):
        """ List with as many items as days of work left. For looping in templates """
        if self.work_left > 0:
            return range(0, self.work_left)
        else:
            return []

    @property
    def cumulative_work_before(self):
        """ How many days of work in tasks before this one """
        preceding_tasks = Task.objects.filter(project=self.project, order__lt=self.order)
        if preceding_tasks.count() == 0:
            return 0

        sum_dict = preceding_tasks.aggregate(models.Sum('work_left'))
        sum_value = sum_dict['work_left__sum']
        return sum_value

    @property
    def cumulative_work_before_list(self):
        """ List with as many items as days of work left. For looping in templates """
        if self.cumulative_work_before > 0:
            return range(0, self.cumulative_work_before)
        else:
            return []

    @property
    def cumulative_work_left(self):
        """ How many days of work until this and all the previous tasks are done """
        return self.cumulative_work_before + self.work_left

    @property
    def finish_date(self):
        days_left = self.cumulative_work_left
        start_date = datetime.date.today()
        return calculate_finish_date(start_date, days_left)

    @property
    def next(self):
        following_tasks = Task.objects.filter(project=self.project, order__gt=self.order).order_by('order')
        if following_tasks.count() == 0:
            return None
        else:
            return following_tasks.first()

    @property
    def prev(self):
        preceding_tasks = Task.objects.filter(project=self.project, order__lt=self.order).order_by('-order')
        if preceding_tasks.count() == 0:
            return None
        else:
            return preceding_tasks.first()

    @property
    def warnings(self):
        if self.phase:
            if self.phase.name == 'finished' or self.phase.name == 'done':
                if self.work_left > 0:
                    return "Task has remaining work: %d" % self.work_left
        return ''


    @property
    def next_phase_url(self):
        if self.phase:
            if self.phase.name == 'pending':
                url = reverse('tasks:task_set_phase_to', args=[self.project.name, self.name, 'ongoing'])
                return { 'title': 'Start', 'url': url}

tasks/templates/tasks/project/archive.html
    <table class="table table-bordered table-striped table-condensed">
        <thead>
        <tr>
            <th style="width:0%"> # </th>
            <th style="width:80%"> Task </th>
            <th> Status </th>
        </tr>
        </thead>
        <tbody>
        {% for task in project.tasks_done %}
        <tr>
            <td> {{ task.order }} </td>
            <td> <a href="{% url 'tasks:task_update' task.project.name task.name %}" title="{{ task.description }}"> {{ task.title }} </a> </td>
            <td class="{{ task.phase.element_class }}"> {{ task.phase.title }} </td>
            {% if task.work_left %}
            <td class="danger"> Task has remaining work: {{ task.work_left }} </td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>

tasks/templates/tasks/project/chart.html
    <table class="day_chart">
        <thead>
        <tr>
            {# <th style="width:0%"> # </th> #}
            <th> Task </th>
            <th colspan="1"> Days </th>
        </tr>
        </thead>
        <tbody>
    {% for task in project.tasks_unfinished.all %}
        <tr>
            <td class="nowrap">
                <a href="{% url 'tasks:task_update' task.project.name task.name %}" title="{{ task.description }}">
                    {{ task.title }}
                </a>
            </td>
            <td class="text-right"> {{ task.work_left }} </td>
            {% for i in task.cumulative_work_before_list %}
            <td class="day-marker white"> &nbsp; </td>
            {% endfor %}
            {% for i in task.work_left_list %}
                {% if task.phase.name == 'ongoing' or task.phase.name == 'continuing' %}
            <td class="day-marker yellow"> &nbsp; </td>
                {% elif task.phase.name == 'blocked' %}
            <td class="day-marker red"> &nbsp; </td>
                {% else %}
            <td class="day-marker green"> &nbsp; </td>
                {% endif %}
            {% endfor %}
            <td class="nowrap" colspan="2" style="border-style: solid;border-width: 1px;border-color:white"> {{ task.finish_date|date:"m-d" }} </td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2"> &nbsp; </th>
        {% for day in project.total_work_left_list %}
            <th class="text-right {% if day.weekday == 0 %}week-start{% endif %}">
                {{ day.day }} <br />
                {{ day.month }}
            </th>
        {% endfor %}
            <th> &nbsp; </th>
        </tr>
        <tr>
            <th colspan="2"> Total: {{ project.total_work_left_string }}</th>
            <th class="text-right"> {{ project.total_work_left }} </th>
            <th class="text-right" colspan="{{ project.total_work_left }}">
                Estimated finish date: {{ project.finish_date|date:"Y-m-d" }}
            </th>
        </tr>
    </tfoot>
    </table>
<br />

tasks/templates/tasks/project/table.html
{% load i18n %}
    <table class="table table-bordered table-striped table-condensed">
        <thead>
        <tr>
            <th style="width:0%"> # </th>
            <th style="width:80%"> {% trans 'Task' %} </th>
            <th> {% trans 'Status' %} </th>
            <th colspan="1"> {% trans 'Work remaining' %} </th>
            <th colspan="1"> {% trans 'Est. finish date' %} </th>
        {% if user.is_authenticated %}
            <th colspan="2"> {% trans 'Move' %} </th>
        {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
        <tr>
            <td> {{ task.order }} </td>
            <td> <a href="{% url 'tasks:task_update' task.project.name task.name %}" title="{{ task.description }}"> {{ task.title }} </a> </td>
            <td class="{{ task.phase.element_class }}"> {{ task.phase.title }} </td>
            <td class="text-right"> {{ task.work_left }} </td>
            {# <td class="text-right"> {{ task.cumulative_work_left }} </td> #}
            <td class="text-right nowrap"> {{ task.finish_date|date:"m-d" }} </td>
            {% if user.is_authenticated %}
            <td> <a class="btn btn-primary btn-xs" href="{% url 'tasks:task_move' task.project.name task.name 'up' %}"> &uarr; </a> </td>
            <td> <a class="btn btn-primary btn-xs" href="{% url 'tasks:task_move' task.project.name task.name 'down' %}"> &darr; </a> </td>
                {% if task.next_phase_url %}
            <td>
                <a class="btn btn-xs btn-primary" href="{{ task.next_phase_url.url }}">
                    {{ task.next_phase_url.title }}
                </a>
            </td>
                {% endif %}
            {% endif %}
            {% if task.warnings %}
            <td class="danger"> {{ task.warnings }} </td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th colspan="3"> {% trans 'Total' %}: {{ project.total_work_left_string }}</th>
            <th class="text-right"> {{ project.total_work_left }} </th>
            <th class="text-right"> {{ project.finish_date|date:"m-d" }} </th>
        </tr>
        </tfoot>
    </table>