mitasny/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('tasks.urls', namespace='tasks')),
]

tasks/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .tasks_user import TasksUserList, TasksUserDetail, TasksUserRegister, TasksUserUpdate, TasksUserDelete
from .project import ProjectList, ProjectListWeekly, ProjectDetail, ProjectWeekly, ProjectCreate, ProjectUpdate, ProjectDelete
from .task import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskMove, TaskSetPhaseTo, TaskDelete

app_name = 'tasks'

urlpatterns = [
    url(r'^$', ProjectList.as_view(), name='home'),
    url(r'^register/$', TasksUserRegister.as_view(), name='register'),
    url(r'^user/(?P<slug>[\w\.-]+)/delete/$', login_required(TasksUserDelete.as_view()), name='user_delete'),
    url(r'^user/(?P<slug>[\w\.-]+)/edit/$', login_required(TasksUserUpdate.as_view()), name='user_update'),
    url(r'^user/(?P<slug>[\w\.-]+)/$', TasksUserDetail.as_view(), name='user'),
    url(r'^project/create/$', login_required(ProjectCreate.as_view()), name='project_create'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/create/$', login_required(TaskCreate.as_view()), name='task_create'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/set_phase_to/(?P<phase>[\w\.-]+)/$', login_required(TaskSetPhaseTo.as_view()), name='task_set_phase_to'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/move/(?P<dir>[\w\.-]+)/$', login_required(TaskMove.as_view()), name='task_move'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/edit/$', TaskUpdate.as_view(), name='task_update'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/delete/$', TaskDelete.as_view(), name='task_delete'),
    url(r'^project/(?P<project_name>[\w\.-]+)/task/(?P<slug>[\w\.-]+)/$', TaskDetail.as_view(), name='task'),
    url(r'^project/(?P<slug>[\w\.-]+)/tab/(?P<tab>[\w\.-]+)/$', ProjectDetail.as_view(), name='project_tab'),
    url(r'^project/(?P<slug>[\w\.-]+)/weekly_report.html$', ProjectWeekly.as_view(), name='project_weekly'),
    url(r'^project/(?P<slug>[\w\.-]+)/edit/$', login_required(ProjectUpdate.as_view()), name='project_update'),
    url(r'^project/(?P<slug>[\w\.-]+)/delete/$', login_required(ProjectDelete.as_view()), name='project_delete'),
    url(r'^project/(?P<slug>[\w\.-]+)/$', ProjectDetail.as_view(), name='project'),
    url(r'^projects/weekly/$', ProjectListWeekly.as_view(), name='projects_weekly'),
    url(r'^projects/$', ProjectList.as_view(), name='projects'),
    url(r'^users/$', TasksUserList.as_view(), name='users'),
    url(r'^tasks/$', TaskList.as_view(), name='tasks'),
]

tasks/models.py
import datetime
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy
from django.contrib.auth.models import User
from .calculate_finish_date import calculate_finish_date


class Project(models.Model):
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URL.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('title'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_projects', on_delete=models.CASCADE)
    edited = models.DateTimeField(auto_now=True)
    edited_by = models.ForeignKey(User, null=True, related_name='edited_projects', on_delete=models.CASCADE)

    @property
    def total_work_left(self):
        if self.tasks.count() == 0:
            return 0

        sum_dict = self.tasks.aggregate(models.Sum('work_left'))
        return sum_dict['work_left__sum']

    @property
    def total_work_left_list(self):
        day_list = []
        total_work = self.total_work_left
        if total_work == 0:
            return day_list

        day = datetime.date.today()
        one_day = datetime.timedelta(days=1)
        for i in range(0, self.total_work_left):
            day_list.append(day)
            day += one_day
            if day.weekday() == 5:
                day += one_day
            if day.weekday() == 6:
                day += one_day

        return day_list

    @property
    def total_work_left_weeks_list(self):
        return range(0, self.total_work_left / 5)

    @property
    def total_work_left_string(self):
        days = self.total_work_left
        weeks = int(days / 5)
        days = days % 5
        months = int(weeks / 4)
        weeks = weeks % 4
        if months > 0:
            return '%d month(s), %d week(s), %d day(s)' % (months, weeks, days)
        elif weeks > 0:
            return '%d week(s), %d day(s)' % (weeks, days)
        else:
            return '%d day(s)' % days

    @property
    def finish_date(self):
        days_left = self.total_work_left
        start_date = datetime.date.today()
        return calculate_finish_date(start_date, days_left)

    def can_edit(self, user):
        if user == self.created_by:
            return True
        return False

    def tasks_by_phase(self, phase):
        return Task.objects.filter(project=self, phase=phase).order_by('order')

    def tasks_by_phase_name(self, phase_name):
        phases = Phase.objects.filter(name=phase_name)
        if phases.count() == 1:
            phase = phases.first()
            return self.tasks_by_phase(phase)
        return Task.objects.none()

    @property
    def tasks_done(self):
        return self.tasks_by_phase_name('done')

    @property
    def tasks_finished(self):
        return self.tasks_by_phase_name('finished')

    @property
    def tasks_ongoing(self):
        return self.tasks_by_phase_name('ongoing')

    @property
    def tasks_continuing(self):
        return self.tasks_by_phase_name('continuing')

    @property
    def tasks_pending(self):
        return self.tasks_by_phase_name('pending')

    @property
    def impediments(self):
        return self.tasks_by_phase_name('impediment')

    @property
    def tasks_unfinished(self):
        excluded_phases = ['finished', 'done', 'impediment']
        tasks = Task.objects.filter(project=self)
        for phase_name in excluded_phases:
            tasks = tasks.exclude(phase__name=phase_name)

        return tasks

    @property
    def tasks_not_done(self):
        done = Phase.objects.get(name='done')
        return Task.objects.filter(project=self).exclude(phase=done)

    @property
    def tasks_last_week(self):
        finished_or_continuing = models.Q(phase__name='finished') | models.Q(phase__name='continuing')
        tasks = Task.objects.filter(project=self).filter(finished_or_continuing)
        return tasks

    @property
    def tasks_this_week(self):
        ongoing_or_continuing = models.Q(phase__name='ongoing') | models.Q(phase__name='continuing')
        tasks = Task.objects.filter(project=self).filter(ongoing_or_continuing)
        return tasks

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tasks:project', args=[self.name])


class Priority(models.Model):
    # Idea, Nice(to have), Minor, Normal, Major, Critical
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URLs.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('title'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    order = models.PositiveSmallIntegerField(default=0)


class TaskStatus(models.Model):
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URLs.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('title'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    order = models.PositiveSmallIntegerField(default=0)


class Phase(models.Model):
    # Blocked, Pending, Ongoing, (Recently)Finished, Done
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URLs.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('title'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    order = models.PositiveSmallIntegerField(default=0)
    element_class = models.CharField(default='', blank=True, max_length=250)  # CSS class to be used in HTML

    def __str__(self):
        # return '%d:%s:%s' % (self.order, self.name, self.title)
        return self.title

    class Meta:
        ordering = ['order', 'title']


class Task(models.Model):
    project = models.ForeignKey(Project, null=False, related_name='tasks', on_delete=models.CASCADE)
    name = models.SlugField(max_length=100, unique=True, verbose_name=ugettext_lazy('name'),
                            help_text=ugettext_lazy('Must be unique. Used in URL.'))
    title = models.CharField(max_length=250, verbose_name=ugettext_lazy('task'))
    description = models.TextField(null=True, blank=True, verbose_name=ugettext_lazy('description'))
    order = models.PositiveSmallIntegerField(default=0)
    priority = models.ForeignKey(Priority, null=True, on_delete=models.CASCADE)
    phase = models.ForeignKey(Phase, null=True, blank=True, on_delete=models.CASCADE)
    # status = models.ForeignKey(TaskStatus, null=True)
    owner = models.ForeignKey(User, null=True, related_name='tasks', on_delete=models.CASCADE)
    work_done = models.PositiveSmallIntegerField(default=0)
    work_left = models.PositiveSmallIntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_tasks', on_delete=models.CASCADE)
    edited = models.DateTimeField(auto_now=True)
    edited_by = models.ForeignKey(User, null=True, related_name='edited_tasks', on_delete=models.CASCADE)

    @property
    def work_left_list(self):
        """ List with as many items as days of work left. For looping in templates """
        if self.work_left > 0:
            return range(0, self.work_left)
        else:
            return []

    @property
    def cumulative_work_before(self):
        """ How many days of work in tasks before this one """
        preceding_tasks = Task.objects.filter(project=self.project, order__lt=self.order)
        if preceding_tasks.count() == 0:
            return 0

        sum_dict = preceding_tasks.aggregate(models.Sum('work_left'))
        sum_value = sum_dict['work_left__sum']
        return sum_value

    @property
    def cumulative_work_before_list(self):
        """ List with as many items as days of work left. For looping in templates """
        if self.cumulative_work_before > 0:
            return range(0, self.cumulative_work_before)
        else:
            return []

    @property
    def cumulative_work_left(self):
        """ How many days of work until this and all the previous tasks are done """
        return self.cumulative_work_before + self.work_left

    @property
    def finish_date(self):
        days_left = self.cumulative_work_left
        start_date = datetime.date.today()
        return calculate_finish_date(start_date, days_left)

    @property
    def next(self):
        following_tasks = Task.objects.filter(project=self.project, order__gt=self.order).order_by('order')
        if following_tasks.count() == 0:
            return None
        else:
            return following_tasks.first()

    @property
    def prev(self):
        preceding_tasks = Task.objects.filter(project=self.project, order__lt=self.order).order_by('-order')
        if preceding_tasks.count() == 0:
            return None
        else:
            return preceding_tasks.first()

    @property
    def warnings(self):
        if self.phase:
            if self.phase.name == 'finished' or self.phase.name == 'done':
                if self.work_left > 0:
                    return "Task has remaining work: %d" % self.work_left
        return ''


    @property
    def next_phase_url(self):
        if self.phase:
            if self.phase.name == 'pending':
                url = reverse('tasks:task_set_phase_to', args=[self.project.name, self.name, 'ongoing'])
                return { 'title': 'Start', 'url': url}

tasks/templates/tasks/project_confirm_delete.html
{% extends "tasks/tasks_base.html" %}
{% load i18n %}
{% block title %} {% trans 'Confirm delete' %} {% endblock %}

{% block content %}
<h1> {% trans 'Are you sure you want to delete project' %}: {{ project.title }}? </h1>

<table class="table">
    <tr>
        <td>
    <form action="{% url 'tasks:project_delete' project.name %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="{% trans 'Delete' %}" />
    </form>
    </td>
        <td>
    <form action="{% url 'tasks:project' project.name %}" method="get">
    {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="{% trans 'Cancel' %}" />
    </form>
        </td>
    </tr>
</table>

{% endblock %}

tasks/templates/tasks/project_detail.html
{% extends "tasks/tasks_base.html" %}
{% load i18n %}

{% block title %} {{ project.title }} {% endblock %}

{% block content %}
<div class="text-right">
    {% trans 'Download' %}
    <a href="{% url 'tasks:project_weekly' project.name %}">weekly_report.html</a>
    <a href="{% url 'tasks:project_weekly' project.name %}?hide_chart=1">[{% trans 'without chart' %}]</a>
    <a href="{% url 'tasks:project_weekly' project.name %}?hide_text=1">[{% trans 'chart only' %}]</a>
</div>
    <h1> {{ project.title }} </h1>
    <table class="table table-bordered">
{% if project.description %}
        <tr>
            <th> {% trans 'Description' %} </th><td> {{ project.description }} </td>
        </tr>
{% endif %}
    </table>

<ul class="nav nav-tabs">
    <li role="presentation" class="{% if tab == 'table' %}active{% endif %}">
        <a href="{% url 'tasks:project_tab' project.name 'table' %}"> {% trans 'Table' %} </a>
    </li>
    <li role="presentation" class="{% if tab == 'chart' %}active{% endif %}">
        <a href="{% url 'tasks:project_tab' project.name 'chart' %}"> {% trans 'Chart' %} </a>
    </li>
    <li role="presentation" class="{% if tab == 'archive' %}active{% endif %}">
        <a href="{% url 'tasks:project_tab' project.name 'archive' %}"> {% trans 'Archive' %} </a>
    </li>
</ul>

{% if project.tasks %}
    {% if tab == 'table' %}
        {% with tasks=project.tasks_not_done %}
            {% include 'tasks/project/table.html' %}
        {% endwith %}
    {% elif tab == 'chart' %}
        {% include 'tasks/project/chart.html' %}
    {% elif tab == 'archive' %}
        {% include 'tasks/project/archive.html' %}
    {% endif %}
{% endif %}

{% if user.is_authenticated %}
<div>
    <a class="btn btn-primary" href="{% url 'tasks:task_create' project.name %}">
        {% trans 'Create task' %}
    </a>
</div>
{% endif %}

{% endblock %}

tasks/templates/tasks/project_form.html
{% extends "tasks/tasks_base.html" %}
{% load i18n %}
{% block title %} Mitasny {% endblock %}

{% block content %}
    {% if project %}
<h1> {{ project.title }} </h1>
<form action="{% url 'tasks:project_update' project.name %}" method="post">
    {% else %}
<h1> {% trans "Create new project" %} </h1>
<form action="{% url 'tasks:project_create' %}" method="post">
    {% endif %}
    {% csrf_token %}

<table class="table">
{{ form.as_table }}
    {% trans "Save" as save_txt %}
    <tr> <td colspan="2"> <input type="submit" class="btn btn-primary" value="{{ save_txt }}"> </td> </tr>
</table>

</form>

{% endblock %}

tasks/templates/tasks/project_list.html
{% extends "tasks/tasks_base.html" %}
{% load i18n %}

{% block title %} Mitasny {% endblock %}
{% block content %}
<div class="text-right">
    {% trans 'Download' %}
    <a href="{% url 'tasks:projects_weekly' %}">weekly_report.html</a>
    <a href="{% url 'tasks:projects_weekly' %}?hide_chart=1">[{% trans 'without charts' %}]</a>
    <a href="{% url 'tasks:projects_weekly' %}?hide_text=1">[{% trans 'charts only' %}]</a>
</div>

    <h1> Projects </h1>
    <table class="table">
        <thead>
            <th> {% trans 'Name' %} </th>
            <th> {% trans 'Tasks' %} </th>
            <th> {% trans 'Work left' %} </th>
            <th> {% trans 'Estimated finish date' %} </th>
        </thead>
        <tbody>
{% for project in project_list %}
        <tr>
            <td> <a href="{{ project.get_absolute_url }}"> {{ project.title }} </a> </td>
            <td> {{ project.tasks.count }} </td>
            <td> {{ project.total_work_left }} </td>
            <td> {{ project.finish_date|date:"Y-m-d" }} </td>
        </tr>
{% endfor %}
{% if user.is_authenticated %}
        <tr>
            <td colspan="4">
                <a class="btn btn-primary" href="{% url 'tasks:project_create' %}">
                    {% trans 'Create project' %}
                </a>
            </td>
        </tr>
{% endif %}
        </tbody>
    </table>
{% endblock %}

tasks/templates/tasks/project_list_weekly.html
{% extends "tasks/tasks_static_base.html" %}
{% load i18n %}

{% block title %} Weekly {% endblock %}

{% block content %}

{% for project in project_list %}
    {% include "tasks/project_weekly_snip.html" %}
{% endfor %}

{% endblock %}

tasks/templates/tasks/project_weekly.html
{% extends "tasks/tasks_static_base.html" %}
{% load i18n %}

{% block title %} {{ project.title }} {% endblock %}

{% block content %}
{% include "tasks/project_weekly_snip.html" %}
{% endblock %}

tasks/templates/tasks/project_weekly_snip.html
{% load i18n %}

{% if not hide_text %}

<h1> {{ project.title }} </h1>
<table>
    {% if project.description %}
    <tr>
        <th> Description </th><td> {{ project.description }} </td>
    </tr>
    {% endif %}
</table>

    {% if project.tasks_last_week %}
<b> {% trans 'Last week' %} </b>
<ul>
        {% for task in project.tasks_last_week.all %}
    <li> {{ task.title }} </li>
            {% if task.description %}
        <ul> <li> {{ task.description }} </li></ul>
            {% endif %}
        {% endfor %}
</ul>
    {% endif %}

    {% if project.tasks_this_week %}
<b> {% trans 'This week' %} </b>
<ul>
    {% for task in project.tasks_this_week.all %}
    <li> {{ task.title }} {% if task.phase.name == 'continuing' %}(continuing){% endif %}</li>
        {% if task.description %}
        <ul> <li> {{ task.description }} </li></ul>
        {% endif %}
    {% endfor %}
</ul>
    {% endif %}

    {% if project.impediments %}
<b> {% trans 'Impediments' %} </b>
<ul>
    {% for task in project.impediments.all %}
    <li> {{ task.title }} </li>
        {% if task.description %}
        <ul> <li> {{ task.description }} </li></ul>
        {% endif %}
    {% endfor %}
</ul>
    {% endif %}
{% endif %}

{% if project.tasks_unfinished and not hide_chart %}
<b> {% trans 'Backlog' %} </b>
    <table>
        <thead>
        <tr>
            <th> {% trans 'Task' %} </th>
            <th colspan="1"> {% trans 'Days' %} </th>
    {% if True %}
            <th colspan="{{ project.total_work_left }}"> &nbsp; </th>
    {% else %}
            <th class="week-marker" colspan="5"> Week 38 </th>
        {% for week in project.total_work_left_weeks_list %}
            <th class="week-marker" colspan="5"> Week {{ week|add:39 }} </th>
        {% endfor %}
    {% endif %}
        </tr>
        </thead>
        <tbody>
    {% for task in project.tasks_unfinished.all %}
        <tr>
            <td class="nowrap"> {{ task.title }} </td>
            <td class="text-right"> {{ task.work_left }} </td>
            {% for i in task.cumulative_work_before_list %}
            <td class="day-marker white"> &nbsp; </td>
            {% endfor %}
            {% for i in task.work_left_list %}
                {% if task.phase.name == 'ongoing' or task.phase.name == 'continuing' %}
            <td class="day-marker yellow"> &nbsp; </td>
                {% elif task.phase.name == 'blocked' %}
            <td class="day-marker red"> &nbsp; </td>
                {% else %}
            <td class="day-marker green"> &nbsp; </td>
                {% endif %}
            {% endfor %}
            <td class="nowrap" colspan="3"> {{ task.finish_date|date:"m-d" }} </td>
        </tr>
    {% endfor %}
        <tr>
            <th colspan="2"> &nbsp; </th>
        {% for day in project.total_work_left_list %}
            <th class="text-right {% if day.weekday == 0 %}week-start{% endif %}">
                {{ day.day }} <br />
                {{ day.month }}
            </th>
        {% endfor %}
            <th> &nbsp; </th>
        </tr>
        <tr>
            <td colspan="1"> <b> {% trans 'Total' %} </b> </td>
            <td class="text-right"> <b> {{ project.total_work_left }} </b> </td>
            <td class="text-right" colspan="{{ project.total_work_left }}">
                {% trans 'Estimated finish date' %}: <b> {{ project.finish_date|date:"Y-m-d" }} </b>
            </td>
        </tr>
        </tbody>
    </table>
{% endif %}
{% if not hide_text %}
<p> <b> {% trans 'Estimated total work required by remaining tasks' %}: {{ project.total_work_left_string }} </b> </p>
{% endif %}

tasks/templates/tasks/task_confirm_delete.html
{% extends "tasks/tasks_base.html" %}
{% load i18n %}
{% block title %} {% trans 'Confirm delete' %} {% endblock %}

{% block content %}
<h1> {% trans 'Are you sure you want to delete task' %}: {{ task.title }}? </h1>

<table class="table">
    <tr>
        <td>
    <form action="{% url 'tasks:task_delete' task.project.name task.name %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="{% trans 'Delete' %}" />
    </form>
    </td>
        <td>
    <form action="{% url 'tasks:task' task.project.name task.name %}" method="get">
    {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="{% trans 'Cancel' %}" />
    </form>
        </td>
    </tr>
</table>

{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends "tasks/tasks_base.html" %}
{% load i18n %}

{% block title %} {{ task.title }} {% endblock %}

{% block content %}

    <h2> <a href="{{ task.project.get_absolute_url }}"> {{ task.project.title }} </a> </h2>
    <h1> {{ task.title }} </h1>
    <table class="table">
        <tr>
            <th> {% trans 'Name' %} </th><td> {{ task.name }} </td>
        </tr>
        <tr>
            <th> {% trans 'Description' %} </th><td> {{ task.description }} </td>
        </tr>
        <tr>
            <td>
                <a class="btn btn-default" href="{% url 'tasks:project' task.project.name %}">
                    {% trans 'Back to project' %}
                </a>
{% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'tasks:task_update' task.project.name task.name %}">
                    {% trans 'Edit' %}
                </a>
{% endif %}
            </td>
            <td>
{% if user.is_authenticated %}
                <a class="btn btn-danger" href="{% url 'tasks:task_delete' task.project.name task.name %}">
                    {% trans 'Delete task' %}
                </a>
{% endif %}
            </td>
        </tr>
    </table>
{% endblock %}

tasks/templates/tasks/task_form.html
{% extends "tasks/tasks_base.html" %}
{% load i18n %}
{% block title %} Mitasny {% endblock %}

{% block content %}
{% if task %}
<h1> {{ task.title }} </h1>
<form action="{% url 'tasks:task_update' task.project.name task.name %}" method="post">
{% elif project %}
<h1> {{ project.title }} </h1>
<h1> {% trans "Create new task" %} </h1>
<form action="{% url 'tasks:task_create' project.name %}" method="post">
{% endif %}
    {% csrf_token %}
<table class="table">
{{ form.as_table }}
    <tr>
        {% trans "Save" as save_txt %}
        <td>
            <input type="submit" class="btn btn-primary" value="{{ save_txt }}">
            <a class="btn btn-default" href="{% url 'tasks:project' project.name %}">
                {% trans 'Back to project' %}
            </a>
        </td>
        {% if task %}
        <td>
            <a class="btn btn-danger" href="{% url 'tasks:task_delete' task.project.name task.name %}">
            {% trans 'Delete' %}
            </a>
        </td>
        {% endif %}
    </tr>
</table>

</form>

{% endblock %}

tasks/templates/tasks/tasks_base.html
<!DOCTYPE html>
<html>
{% load i18n %}
  <head>
    <meta charset="UTF-8">
    <title> {% block title %}Mitasny{% endblock %}</title>
    <style>
      table.day_chart {
        border-style: solid;
        border-width: 1px 0px;
        border-color: #aaaaaa;
        border-collapse: separate;
        border-spacing: 2px 3px;
        padding: 5px;
      }

      td.day-marker {
        border-style: solid;
        border-width: 1px;
        width: 18px;
      }

      td.white {
        border-color: #aaaaaa;
      }

      td.green {
        border-color: #aaaaaa;
        background-color:green;
      }

      td.yellow {
        border-color: rgb(180, 180, 0);
        background-color: rgb(180, 180, 0);
      }

      td.red {
        border-color: red;
        background-color: red;
      }

      th.week-start {
        text-align: center;
        border-style: solid;
        border-width: 0px 0px 0px 2px;
        border-color: #aaaaaa;
      }

      .nowrap {
        white-space: nowrap;
      }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="{% if project_list %}active{% endif %}">
            <a href="{% url 'tasks:projects' %}"> {% trans 'Projects' %} </a>
        </li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="{% if user_list %}active{% endif %}">
            <a href="{% url 'tasks:users' %}"> {% trans 'Users' %} </a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
{% if user.is_authenticated %}
        <li> <a href="{% url 'tasks:user' user.username %}">{{ user.username }}</a> </li>
        <li> <a href="{% url 'logout' %}?next={% url 'tasks:projects' %}"> {% trans 'Logout' %} </a> </li>
{% else %}
        <li> <a href="{% url 'login' %}"> {% trans 'Login' %} </a> </li>
        <li> <a href="{% url 'tasks:register' %}"> {% trans 'Register' %} </a> </li>
{% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
{% if messages %}
  {% for message in messages %}
  <div> {{ message }} </div>
  {% endfor %}
{% endif%}
{% block content %}
{% endblock %}
</div>
  </body>
</html>